# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  app_name = 'test'
  repos_dir = File.expand_path("#{File.dirname(__FILE__)}/../")+"/"
  config.vm.synced_folder "#{repos_dir}", "/usr/share/#{app_name}", :create => true, :owner=> 'vagrant', :group=> 'vagrant', :mount_options => ["uid=48,gid=48,dmode=0777,fmode=0777"]
  config.vm.network "forwarded_port", guest: 80, host: 11080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 22, host: 11022, host_ip: "127.0.0.1"

  config.vm.provision :shell, path: "vagrant.sh", privileged: false, args: "#{app_name}"
end
